# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-14 14:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resources', '0034_add_reserver_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeReservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id_hash', models.CharField(db_index=True, editable=False, max_length=32)),
                ('principal_email', models.EmailField(editable=False, max_length=254)),
                ('_item_id', models.CharField(blank=True, db_column='item_id', editable=False, max_length=200)),
                ('_change_key', models.CharField(blank=True, db_column='change_key', editable=False, max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='time of creation')),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='time of modification')),
                ('reservation', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.DO_NOTHING, to='resources.Reservation')),
            ],
            options={
                'verbose_name_plural': 'Exchange reservations',
                'verbose_name': 'Exchange reservation',
            },
        ),
        migrations.CreateModel(
            name='ExchangeResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_to_respa', models.BooleanField(db_index=True, default=True, help_text='if disabled, events will not be synced from the Exchange calendar to Respa', verbose_name='sync Exchange to Respa')),
                ('sync_from_respa', models.BooleanField(db_index=True, default=True, help_text='if disabled, new events will not be synced from Respa to the Exchange calendar; pre-existing events continue to be updated', verbose_name='sync Respa to Exchange')),
                ('principal_email', models.EmailField(help_text='the email address for this resource in Exchange', max_length=254, unique=True, verbose_name='principal email')),
                ('resource', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='resources.Resource', verbose_name='resource')),
            ],
            options={
                'verbose_name_plural': 'Exchange resources',
                'verbose_name': 'Exchange resource',
            },
        ),
    ]
