# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-15 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('respa_exchange', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangereservation',
            name='managed_in_exchange',
            field=models.BooleanField(db_index=True, default=False, editable=False),
        ),
    ]
