# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-18 08:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('respa_exchange', '0002_managed_in_exchange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangereservation',
            name='exchange',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='respa_exchange.ExchangeConfiguration'),
        ),
        migrations.AlterField(
            model_name='exchangereservation',
            name='reservation',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exchange_reservation', to='resources.Reservation'),
        ),
        migrations.AlterField(
            model_name='exchangeresource',
            name='exchange',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resources', to='respa_exchange.ExchangeConfiguration', verbose_name='Exchange configuration'),
        ),
        migrations.AlterField(
            model_name='exchangeresource',
            name='resource',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='exchange_resource', to='resources.Resource', verbose_name='resource'),
        ),
    ]
