# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 10:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('respa_exchange', '0004_add_organizer_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x500_address', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('email_address', models.CharField(db_index=True, max_length=200)),
                ('name', models.CharField(max_length=100)),
                ('given_name', models.CharField(blank=True, max_length=100, null=True)),
                ('surname', models.CharField(blank=True, max_length=100, null=True)),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='users', to='respa_exchange.ExchangeConfiguration', verbose_name='Exchange configuration')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exchange_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='exchangereservation',
            name='organizer_email',
        ),
        migrations.AddField(
            model_name='exchangereservation',
            name='organizer',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='respa_exchange.ExchangeUser'),
        ),
        migrations.AlterUniqueTogether(
            name='exchangeuser',
            unique_together=set([('exchange', 'x500_address'), ('exchange', 'email_address')]),
        ),
    ]
