# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-02 19:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('respa_exchange', '0005_add_exchange_user_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangereservation',
            name='organizer',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='respa_exchange.ExchangeUser'),
        ),
        migrations.AlterField(
            model_name='exchangeuser',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exchange_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
