# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-17 13:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('respa_exchange', '0006_support_for_django_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeUserX500Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='x500_addresses', to='respa_exchange.ExchangeConfiguration')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='x500_addresses', to='respa_exchange.ExchangeUser')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='exchangeuserx500address',
            unique_together=set([('exchange', 'address')]),
        ),
    ]
