# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-17 13:18
from __future__ import unicode_literals

from django.db import migrations


def migrate_x500_addresses(apps, schema_editor):
    ExchangeUser = apps.get_model('respa_exchange', 'ExchangeUser')
    ExchangeUserX500Address = apps.get_model('respa_exchange', 'ExchangeUserX500Address')

    for user in ExchangeUser.objects.all():
        addr = ExchangeUserX500Address(
            exchange_id=user.exchange_id,
            user=user,
            address=user.x500_address
        )
        addr.save()


class Migration(migrations.Migration):

    dependencies = [
        ('respa_exchange', '0007_add_x500_address_model'),
    ]

    operations = [
        migrations.RunPython(migrate_x500_addresses),
    ]
