# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-17 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('respa_exchange', '0009_remove_exchange_user_x500_address_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangeuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
