# Generated by Django 2.1.7 on 2019-04-08 19:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resources', '0075_alter_resource_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('waiting', 'waiting'), ('confirmed', 'confirmed'), ('rejected', 'rejected')], default='waiting', max_length=32, verbose_name='status')),
                ('order_number', models.CharField(default=uuid.uuid4, max_length=64, unique=True, verbose_name='order number')),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='order', to='resources.Reservation', verbose_name='reservation')),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'orders',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='quantity')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_lines', to='payments.Order', verbose_name='order')),
            ],
            options={
                'verbose_name': 'order line',
                'verbose_name_plural': 'order lines',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('rent', 'rent')], default='rent', max_length=32, verbose_name='type')),
                ('code', models.CharField(max_length=255, verbose_name='code')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('pretax_price', models.DecimalField(decimal_places=2, default='0.00', max_digits=14, verbose_name='pretax price')),
                ('tax_percentage', models.PositiveSmallIntegerField(default=24, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='tax percentage')),
                ('price_type', models.CharField(choices=[('per_hour', 'per hour')], default='per_hour', max_length=32, verbose_name='price type')),
                ('resources', models.ManyToManyField(blank=True, related_name='products', to='resources.Resource', verbose_name='resource')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='orderline',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_lines', to='payments.Product', verbose_name='product'),
        ),
    ]
