# Generated by Django 2.2.13 on 2020-09-28 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_url',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='payment url'),
        ),
    ]
