# Generated by Django 2.1.7 on 2019-04-29 07:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='archived_at',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(9999, 12, 31, 0, 0, tzinfo=utc), editable=False, verbose_name='archived_at'),
        ),
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='product_id',
            field=models.PositiveIntegerField(db_index=True, default=1, editable=False, verbose_name='product ID'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('archived_at', 'product_id')},
        ),
    ]
