# Generated by Django 2.2.13 on 2020-09-28 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_order_payment_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='confirmed_by_staff_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='confirmed by staff at'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_requested_order',
            field=models.BooleanField(default=False, verbose_name='is requested order'),
        ),
    ]
