# Generated by Django 2.2.13 on 2020-10-05 10:20

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0095_resource_attachments_allow_empty'),
        ('payments', '0003_order_requested_payment_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationCustomPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='price including VAT')),
                ('price_type', models.CharField(choices=[('half', 'half'), ('free', 'free'), ('custom', 'custom')], max_length=32, verbose_name='price type')),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='custom_price', to='resources.Reservation', verbose_name='custom price')),
            ],
            options={
                'verbose_name': 'custom price',
                'verbose_name_plural': 'custom prices',
            },
        ),
    ]
