# Generated by Django 2.2.13 on 2020-10-26 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_reservationcustomprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_type',
            field=models.CharField(choices=[('per_multiday_duration_unit', 'per multiday duration unit'), ('per_period', 'per period'), ('fixed', 'fixed')], default='per_period', max_length=32, verbose_name='price type'),
        ),
        migrations.AlterField(
            model_name='reservationcustomprice',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='price including VAT'),
        ),
    ]
