# Generated by Django 2.1.7 on 2019-05-13 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_char_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payer_address_city',
            field=models.CharField(default='', max_length=100, verbose_name='payer address city'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='payer_address_zip',
            field=models.CharField(default='', max_length=16, verbose_name='payer address zip'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='payer_address_street',
            field=models.CharField(default='', max_length=255, verbose_name='payer address street'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='payer_email_address',
            field=models.EmailField(default='', max_length=254, verbose_name='payer email address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='payer_first_name',
            field=models.CharField(default='', max_length=100, verbose_name='payer first name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='payer_last_name',
            field=models.CharField(default='', max_length=100, verbose_name='payer last name'),
            preserve_default=False,
        ),
    ]
