# Generated by Django 2.1.7 on 2019-06-03 21:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_add_payer_fields_to_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pretax_price',
            field=models.DecimalField(decimal_places=10, max_digits=19, validators=[django.core.validators.MinValueValidator(0)], verbose_name='pretax price'),
        ),
    ]
