# Generated by Django 2.1.7 on 2019-06-05 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_product_price_accuracy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='resources.Reservation', verbose_name='reservation'),
        ),
    ]
