# Generated by Django 2.1.7 on 2019-06-06 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_allow_multiple_orders_per_reservation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='status',
            new_name='state'
        ),
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(choices=[('waiting', 'waiting'), ('confirmed', 'confirmed'),
                                            ('rejected', 'rejected'), ('expired', 'expired')],
                                   default='waiting', max_length=32, verbose_name='state'),
        ),
    ]
