# Generated by Django 2.1.7 on 2019-06-17 12:52

from django.db import migrations, models
import resources.models.utils


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_add_order_cancelled_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default=resources.models.utils.generate_id, max_length=64, unique=True, verbose_name='order number'),
        ),
    ]
