# Generated by Django 2.1.7 on 2019-06-26 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0013_add_fixed_price_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='reservation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='order', to='resources.Reservation', verbose_name='reservation'),
        ),
    ]
