# Generated by Django 2.1.7 on 2019-07-11 22:23
from datetime import timedelta
from decimal import Decimal

from django.db import migrations, models

from payments.utils import round_price


def convert_per_hour_price_to_per_period_price(apps, schema_editor):
    Product = apps.get_model('payments', 'Product')
    for product in Product.objects.filter(price_type='per_hour'):
        price = product.price * round_price(Decimal(timedelta(hours=1) / product.price_period))
        Product.objects.filter(id=product.id).update(price=price, price_type='per_period')


def convert_per_period_price_to_per_hour_price(apps, schema_editor):
    Product = apps.get_model('payments', 'Product')
    for product in Product.objects.filter(price_type='per_period'):
        price = product.price * round_price(Decimal(product.price_period / timedelta(hours=1)))
        Product.objects.filter(id=product.id).update(price=price, price_type='per_hour')


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0019_add_product_type_extra'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_period',
            field=models.DurationField(blank=True, default=timedelta(0, 3600), null=True, verbose_name='price period'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_type',
            field=models.CharField(choices=[('per_period', 'per period'), ('fixed', 'fixed')], default='per_period', max_length=32, verbose_name='price type'),
        ),
        migrations.RunPython(convert_per_hour_price_to_per_period_price, convert_per_period_price_to_per_hour_price),
    ]
