# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-14 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0038_add_municipality_to_unit'),
        ('users', '0004_auto_20160729_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_resources',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='resources.Resource', verbose_name='Favorite resources'),
        ),
    ]
