# Generated by Django 2.2.9 on 2020-03-10 11:37
# https://docs.djangoproject.com/en/3.0/releases/2.0/#abstractuser-last-name-max-length-increased-to-150

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_fill_is_general_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
    ]
