
sudo: required
dist: trusty

services:
  - docker

language: python
python:
  - '3.5'
  - '3.6'
  - '3.7-dev'

matrix:
  allow_failures:
  - python: 3.7-dev
  
cache: pip

# Respa uses int4range (IntegerRangeField) so needs at least Postgres9.2
# As of 2017-08 the new travis trusty images have broken postgis,
# so we have to specify the exact postgres version to install right addons.
# They also seem to miss the GDAL C library...
addons:
  postgresql: "9.6"
  apt:
    packages:
      - libgdal-dev
      - postgresql-9.6-postgis-2.3

install: true 
#'pip install codecov -r requirements.txt'

# before_script:
#   - psql template1 -c 'create extension hstore;'

#script: pytest --cov . resources respa_exchange caterings

script: true

after_success:
  # - codecov
  - env
