version: '3'

networks:
  network:

services:
  db:
    container_name: respa-db
    build: ./docker/postgres/
    restart: always
    environment:
        POSTGRES_USER: respa
        POSTGRES_PASSWORD: respa
        POSTGRES_DB: respa
    volumes:
      - db_data:/var/lib/postgresql
    networks:
      - network
  api:
    container_name: respa-api
    build:
      context: ./
      dockerfile: ./docker/dev/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    environment:
      - DEBUG=1
      - DATABASE_URL=postgis://respa:respa@db/respa
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - network
  varaamo:
    container_name: varaamo
    build:
      context: ./varaamo
    volumes:
      - node_modules:/usr/src/app/node_modules
      - ./varaamo:/usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - api
    networks:
      - network
  nginx:
    image: nginx
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - network
    depends_on:
      - api
      - db
      - varaamo


volumes:
    db_data:
    node_modules:
