# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-29 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kulkunen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesscontrolgrant',
            name='install_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accesscontrolgrant',
            name='remove_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accesscontrolgrant',
            name='state',
            field=models.CharField(choices=[('requested', 'requested'), ('installed', 'installed'), ('cancelled', 'cancelled'), ('removing', 'removing'), ('removed', 'removed')], default='requested', editable=False, help_text='State of the grant', max_length=20),
        ),
        migrations.AlterIndexTogether(
            name='accesscontrolgrant',
            index_together=set([('resource', 'state')]),
        ),
    ]
