# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-15 12:37
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resources', '0052_add_can_access_reservation_comments_perm'),
    ]

    operations = [
        migrations.CreateModel(
            name='CateringOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='time of creation')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='time of modification')),
                ('invoicing_data', models.CharField(max_length=100, verbose_name='Invoicing data')),
                ('message', models.TextField(blank=True, verbose_name='Message')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catering_orders', to='resources.Reservation', verbose_name='Reservation')),
            ],
            options={
                'verbose_name': 'Catering order',
                'verbose_name_plural': 'Catering orders',
            },
        ),
        migrations.CreateModel(
            name='CateringOrderLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, validators=(django.core.validators.MinValueValidator(1),), verbose_name='Quantity')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_lines', to='caterings.CateringOrder', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Catering order line',
                'verbose_name_plural': 'Catering order lines',
            },
        ),
        migrations.CreateModel(
            name='CateringProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='time of creation')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='time of modification')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('name_fi', models.CharField(max_length=100, null=True, verbose_name='Name')),
                ('name_en', models.CharField(max_length=100, null=True, verbose_name='Name')),
                ('name_sv', models.CharField(max_length=100, null=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('description_fi', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('description_sv', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Catering product',
                'verbose_name_plural': 'Catering products',
            },
        ),
        migrations.CreateModel(
            name='CateringProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='time of creation')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='time of modification')),
                ('name', models.CharField(max_length=100, verbose_name='Catering product category')),
                ('name_fi', models.CharField(max_length=100, null=True, verbose_name='Catering product category')),
                ('name_en', models.CharField(max_length=100, null=True, verbose_name='Catering product category')),
                ('name_sv', models.CharField(max_length=100, null=True, verbose_name='Catering product category')),
            ],
            options={
                'verbose_name': 'Catering product category',
                'verbose_name_plural': 'Catering product categories',
            },
        ),
        migrations.CreateModel(
            name='CateringProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='time of creation')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='time of modification')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('price_list_url', models.URLField(blank=True, verbose_name='Price list URL')),
                ('price_list_url_fi', models.URLField(blank=True, null=True, verbose_name='Price list URL')),
                ('price_list_url_en', models.URLField(blank=True, null=True, verbose_name='Price list URL')),
                ('price_list_url_sv', models.URLField(blank=True, null=True, verbose_name='Price list URL')),
                ('units', models.ManyToManyField(blank=True, related_name='catering_providers', to='resources.Unit', verbose_name='Units')),
            ],
            options={
                'verbose_name': 'Catering provider',
                'verbose_name_plural': 'Catering providers',
            },
        ),
        migrations.AddField(
            model_name='cateringproductcategory',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catering_product_categories', to='caterings.CateringProvider', verbose_name='Catering provider'),
        ),
        migrations.AddField(
            model_name='cateringproduct',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='caterings.CateringProductCategory', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='cateringorderline',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catering_order_line', to='caterings.CateringProduct', verbose_name='Product'),
        ),
    ]
