# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-06 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caterings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cateringorder',
            name='serving_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Serving time'),
        ),
    ]
