# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caterings', '0002_add_catering_serving_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cateringorder',
            name='invoicing_data',
            field=models.TextField(verbose_name='Invoicing data'),
        ),
    ]
