# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caterings', '0003_change_invoicing_data_to_textfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='cateringprovider',
            name='notification_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Notification email'),
        ),
    ]
