# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-10 11:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caterings', '0004_add_notification_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cateringorder',
            options={'ordering': ('id',), 'verbose_name': 'Catering order', 'verbose_name_plural': 'Catering orders'},
        ),
        migrations.AlterModelOptions(
            name='cateringproduct',
            options={'ordering': ('name',), 'verbose_name': 'Catering product', 'verbose_name_plural': 'Catering products'},
        ),
        migrations.AlterModelOptions(
            name='cateringproductcategory',
            options={'ordering': ('provider', 'name'), 'verbose_name': 'Catering product category', 'verbose_name_plural': 'Catering product categories'},
        ),
        migrations.AlterModelOptions(
            name='cateringprovider',
            options={'ordering': ('id',), 'verbose_name': 'Catering provider', 'verbose_name_plural': 'Catering providers'},
        ),
        migrations.AddField(
            model_name='cateringorder',
            name='provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catering_orders', to='caterings.CateringProvider', verbose_name='Catering provider'),
        ),
    ]
