# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-10 11:27
from __future__ import unicode_literals

from django.db import migrations


def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    CateringOrder = apps.get_model("caterings", "CateringOrder")
    for order in CateringOrder.objects.all():
        order.provider = order.order_lines.first().product.category.provider
        order.save(update_fields=['provider'])


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('caterings', '0005_add_provider_field_to_order'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
