# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-10 11:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caterings', '0006_migrate_provider_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cateringorder',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='catering_orders', to='caterings.CateringProvider', verbose_name='Catering provider'),
        ),
    ]
