# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-22 14:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resources', '0070_reservable_min_and_max_days_in_advance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Berth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width_cm', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Berth width')),
                ('depth_cm', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Berth depth')),
                ('length_cm', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Berth length')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('type', models.CharField(choices=[('dock', 'dock'), ('ground', 'ground'), ('number', 'number')], default='dock', max_length=20, verbose_name='Berth type')),
                ('is_disabled', models.BooleanField(default=False)),
                ('reserving', models.DateTimeField(blank=True, null=True, verbose_name='Reserving')),
                ('is_deleted', models.BooleanField(default=False)),
                ('reserving_staff_member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('resource', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='resources.Resource', verbose_name='Resource')),
            ],
        ),
        migrations.CreateModel(
            name='BerthReservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Is paid')),
                ('reserver_ssn', models.CharField(blank=True, default='', max_length=11, verbose_name='Reserver ssn')),
                ('state_updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Time of modification')),
                ('is_paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Time of payment')),
                ('key_returned', models.BooleanField(default=False, verbose_name='Key returned')),
                ('key_returned_at', models.DateTimeField(blank=True, null=True, verbose_name='Time of key returned')),
                ('renewal_code', models.CharField(blank=True, default=None, max_length=40, null=True, verbose_name='Renewal code')),
                ('renewal_notification_month_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Renewal notification month before end sent at')),
                ('renewal_notification_week_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Renewal notification week before end sent at')),
                ('renewal_notification_day_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Renewal notification day before end sent at')),
                ('end_notification_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='End notification sent at')),
                ('key_return_notification_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Key return notification sent at')),
                ('berth', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='berth_reservations', to='respa_berth.Berth', verbose_name='Berth')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='respa_berth.BerthReservation')),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='berth_reservation', to='resources.Reservation', verbose_name='Reservation')),
            ],
        ),
        migrations.CreateModel(
            name='GroundBerthPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Time of creation')),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Time of modification')),
                ('purchase_code', models.CharField(max_length=40, verbose_name='Purchase code')),
                ('reserver_name', models.CharField(blank=True, max_length=100, verbose_name='Reserver name')),
                ('reserver_email_address', models.EmailField(blank=True, max_length=254, verbose_name='Reserver email address')),
                ('reserver_phone_number', models.CharField(blank=True, max_length=30, verbose_name='Reserver phone number')),
                ('reserver_address_street', models.CharField(blank=True, max_length=100, verbose_name='Reserver address street')),
                ('reserver_address_zip', models.CharField(blank=True, max_length=30, verbose_name='Reserver address zip')),
                ('reserver_address_city', models.CharField(blank=True, max_length=100, verbose_name='Reserver address city')),
                ('vat_percent', models.IntegerField(choices=[(0, '0'), (10, '10'), (14, '24'), (24, '24')], default=24)),
                ('price_vat', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('product_name', models.CharField(blank=True, max_length=100, verbose_name='Product name')),
                ('purchase_process_started', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Purchase process started')),
                ('purchase_process_success', models.DateTimeField(blank=True, null=True, verbose_name='Purchase process success')),
                ('purchase_process_failure', models.DateTimeField(blank=True, null=True, verbose_name='Purchase process failure')),
                ('purchase_process_notified', models.DateTimeField(blank=True, null=True, verbose_name='Purchase process notified')),
                ('purchase_process_report_seen', models.DateTimeField(blank=True, null=True, verbose_name='Purchase process notified')),
                ('payment_service_order_number', models.IntegerField(blank=True, null=True)),
                ('payment_service_timestamp', models.CharField(blank=True, max_length=100, null=True, verbose_name='Payment service timestamp')),
                ('payment_service_paid', models.CharField(blank=True, max_length=100, null=True, verbose_name='Payment service paid')),
                ('payment_service_method', models.IntegerField(blank=True, null=True)),
                ('payment_service_return_authcode', models.CharField(blank=True, max_length=100, null=True, verbose_name='Reserver address street')),
                ('finished', models.DateTimeField(blank=True, null=True, verbose_name='Purchase finished')),
                ('berth_reservation', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='respa_berth.BerthReservation', verbose_name='BerthReservation')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_modified', to=settings.AUTH_USER_MODEL, verbose_name='Modified by')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SMSMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Time of creation')),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Time of modification')),
                ('message_body', models.TextField()),
                ('to_phone_number', models.CharField(blank=True, max_length=30, verbose_name='Reserver phone number')),
                ('success', models.BooleanField(default=False)),
                ('twilio_id', models.CharField(blank=True, max_length=100)),
                ('berth_reservation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_messages', to='respa_berth.BerthReservation', verbose_name='Reservation')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='smsmessage_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='smsmessage_modified', to=settings.AUTH_USER_MODEL, verbose_name='Modified by')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
