# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-09 05:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resources', '0051_auto_20170509_0758'),
    ]

    operations = [
        migrations.CreateModel(
            name='Berth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width_cm', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Berth width')),
                ('depth_cm', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Berth depth')),
                ('length_cm', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Berth length')),
                ('type', models.CharField(choices=[('dock', 'dock'), ('ground', 'ground'), ('number', 'number')], default='dock', max_length=20, verbose_name='Berth type')),
                ('resource', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='resources.Resource', verbose_name='Resource')),
            ],
        ),
    ]
