# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-12 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmlvaraus', '0002_hmlreservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='hmlreservation',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Is paid'),
        ),
    ]
