# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-22 07:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hmlvaraus', '0003_hmlreservation_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='hmlreservation',
            name='state_updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Time of modification'),
        ),
    ]
