# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-29 07:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmlvaraus', '0005_hmlreservation_is_paid_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='berth',
            name='is_disabled',
            field=models.BooleanField(default=False),
        ),
    ]
