# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-06 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmlvaraus', '0006_berth_is_disabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='berth',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
