# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-09 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmlvaraus', '0007_berth_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='hmlreservation',
            name='key_returned',
            field=models.BooleanField(default=False, verbose_name='Key returned'),
        ),
    ]
