# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-26 07:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hmlvaraus', '0009_hmlreservation_key_returned_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='hmlreservation',
            name='berth',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hml_reservations', to='hmlvaraus.Berth', verbose_name='Berth'),
        ),
    ]
