# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-06 14:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resources', '0075_resource_use_payments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Time of creation')),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Time of modification')),
                ('verification_code', models.CharField(blank=True, default='', max_length=40, verbose_name='Verification code')),
                ('order_process_started', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Order process started')),
                ('order_process_success', models.DateTimeField(blank=True, null=True, verbose_name='Order process success')),
                ('order_process_failure', models.DateTimeField(blank=True, null=True, verbose_name='Order process failure')),
                ('order_process_notified', models.DateTimeField(blank=True, null=True, verbose_name='Order process notified')),
                ('order_process_report_seen', models.DateTimeField(blank=True, null=True, verbose_name='Order process notified')),
                ('payment_service_order_number', models.IntegerField(blank=True, null=True)),
                ('payment_service_timestamp', models.CharField(blank=True, max_length=100, null=True, verbose_name='Payment service timestamp')),
                ('payment_service_paid', models.CharField(blank=True, max_length=100, null=True, verbose_name='Payment service paid')),
                ('payment_service_method', models.IntegerField(blank=True, null=True)),
                ('payment_service_return_authcode', models.CharField(blank=True, max_length=100, null=True, verbose_name='Payment service return authcode')),
                ('finished', models.DateTimeField(blank=True, null=True, verbose_name='Order finished')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_modified', to=settings.AUTH_USER_MODEL, verbose_name='Modified by')),
                ('reservation', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='resources.Reservation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sku',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Time of creation')),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Time of modification')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Price')),
                ('vat', models.DecimalField(decimal_places=2, default=24.0, max_digits=6, verbose_name='VAT')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('date_start', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date start')),
                ('date_end', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date end')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sku_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('duration_slot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skus', to='resources.DurationSlot')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sku_modified', to=settings.AUTH_USER_MODEL, verbose_name='Modified by')),
            ],
            options={
                'verbose_name': 'Stock keeping unit',
                'verbose_name_plural': 'Stock keeping units',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='sku',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='respa_payments.Sku'),
        ),
    ]
