# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-11 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('respa_payments', '0002_auto_20190306_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_service_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Payment service amount'),
        ),
    ]
