# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-09-30 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('respa_payments', '0003_auto_20190311_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sku_name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='SKU name'),
        ),
    ]
