# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-10 13:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import parler.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('reservation_requested', 'Reservation requested'), ('reservation_requested_official', 'Reservation requested official'), ('reservation_cancelled', 'Reservation cancelled'), ('reservation_confirmed', 'Reservation confirmed'), ('reservation_denied', 'Reservation_denied'), ('reservation_created_with_access_code', 'Reservation created with access code')], db_index=True, max_length=100, unique=True, verbose_name='Type')),
            ],
            options={
                'verbose_name': 'Notification template',
                'verbose_name_plural': 'Notification templates',
            },
            # Commented out because bases are set incorrectly and that would break our data migration
            # see https://github.com/django-parler/django-parler/issues/157
            # bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='NotificationTemplateTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('short_message', models.TextField(blank=True, help_text='Short notification text for e.g. SMS messages', verbose_name='Short message')),
                ('subject', models.CharField(help_text='Subject for email notifications', max_length=200, verbose_name='Subject')),
                ('body', models.TextField(help_text='Text body for email notifications', verbose_name='body')),
                ('master', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='notifications.NotificationTemplate')),
            ],
            options={
                'managed': True,
                'db_table': 'notifications_notificationtemplate_translation',
                'verbose_name': 'Notification template Translation',
                'default_permissions': (),
                'db_tablespace': '',
            },
        ),
        migrations.AlterUniqueTogether(
            name='notificationtemplatetranslation',
            unique_together=set([('language_code', 'master')]),
        ),
    ]
