# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-01 13:11
from __future__ import unicode_literals

from django.db import migrations

FI_BODY = """
Varauksesi on hyväksytty.

Tila: {{ resource }}
Toimipiste: {{ unit }}
Alkaa: {{ begin }}
Loppuu: {{ end }}

Varauksen voitte perua viisi päivää ennen varauksen alkua. Varauksen
peruminen tehdään tilasta vastaavan henkilökunnan kautta. Tarkemmat
tiedot perumiseen löydätte Varaamon omista varauksista kirjautumalla
palveluun.

{% if extra_content is defined %}
{{ extra_content }}
{% endif %}
"""

EN_BODY = """
Your reservation has been confirmed.

Resource: {{ resource }}
Unit: {{ unit }}
Starts: {{ begin }}
Ends: {{ end }}

It is possible to cancel the reservation five days before the start of
your reservation. All cancellations are done through personnel. Further
information for cancelling your reservation can be found from Varaamo's
"Omat varaukset" section which you can find when you are logged in to the
service.

{% if extra_content is defined %}
{{ extra_content }}
{% endif %}
"""


def modify_notification_templates(NotificationTemplate, NotificationTemplateTranslation):
    nt = NotificationTemplate.objects.get(type='reservation_confirmed')
    fi = NotificationTemplateTranslation.objects.get(
        master_id=nt.id, language_code='fi')
    en = NotificationTemplateTranslation.objects.get(
        master_id=nt.id, language_code='en')
    en.body = EN_BODY
    fi.body = FI_BODY
    fi.save()
    en.save()


def forwards(apps, schema_editor):
    NotificationTemplate = apps.get_model('notifications', 'NotificationTemplate')
    NotificationTemplateTranslation = apps.get_model('notifications', 'NotificationTemplateTranslation')
    modify_notification_templates(NotificationTemplate, NotificationTemplateTranslation)


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_add_more_notification_types'),
    ]

    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop)
    ]
