# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-24 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_add_more_notification_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationtemplatetranslation',
            name='html_body',
            field=models.TextField(blank=True, help_text='HTML body for email notifications', verbose_name='HTML body'),
        ),
        migrations.AlterField(
            model_name='notificationtemplatetranslation',
            name='body',
            field=models.TextField(blank=True, help_text='Text body for email notifications', verbose_name='Body'),
        ),
    ]
