# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0030_add_reservation_extra_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unit',
            options={'permissions': (('can_approve_reservation', 'Can approve reservation'),), 'verbose_name': 'unit', 'verbose_name_plural': 'units'},
        ),
    ]
