# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 19:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resources', '0031_can_approve_reservation_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approved_reservations', to=settings.AUTH_USER_MODEL, verbose_name='Approver'),
        ),
    ]
