# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-05 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0032_add_reservation_approver'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='responsible_contact_info',
            field=models.TextField(blank=True, verbose_name='Responsible contact info'),
        )
    ]
