# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-05 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0033_add_responsible_contact_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='reserver_email_address',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Reserver email address'),
        )
    ]
