# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0036_migrate_reserver_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='business_id',
        ),
    ]
