# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-19 14:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resources', '0038_add_municipality_to_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermsOfUse',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Time of creation')),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Time of modification')),
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('name_fi', models.CharField(max_length=200, null=True, verbose_name='Name')),
                ('name_en', models.CharField(max_length=200, null=True, verbose_name='Name')),
                ('name_sv', models.CharField(max_length=200, null=True, verbose_name='Name')),
                ('text', models.TextField(verbose_name='Text')),
                ('text_fi', models.TextField(null=True, verbose_name='Text')),
                ('text_en', models.TextField(null=True, verbose_name='Text')),
                ('text_sv', models.TextField(null=True, verbose_name='Text')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='termsofuse_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='termsofuse_modified', to=settings.AUTH_USER_MODEL, verbose_name='Modified by')),
            ],
            options={
                'verbose_name': 'terms of use',
                'verbose_name_plural': 'terms of use',
            },
        ),
        migrations.AddField(
            model_name='resource',
            name='specific_terms',
            field=models.TextField(blank=True, verbose_name='Specific terms'),
        ),
        migrations.AddField(
            model_name='resource',
            name='specific_terms_en',
            field=models.TextField(blank=True, null=True, verbose_name='Specific terms'),
        ),
        migrations.AddField(
            model_name='resource',
            name='specific_terms_fi',
            field=models.TextField(blank=True, null=True, verbose_name='Specific terms'),
        ),
        migrations.AddField(
            model_name='resource',
            name='specific_terms_sv',
            field=models.TextField(blank=True, null=True, verbose_name='Specific terms'),
        ),
        migrations.AddField(
            model_name='resource',
            name='generic_terms',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resources.TermsOfUse', verbose_name='Generic terms'),
        ),
    ]
