# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 12:58
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0040_resource_specific_notification_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='max_price_per_hour',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Max price per hour'),
        ),
        migrations.AddField(
            model_name='resource',
            name='min_price_per_hour',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Min price per hour'),
        ),
    ]
