# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-06 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0041_add_resource_price_per_hour_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='access_code',
            field=models.CharField(blank=True, max_length=32, verbose_name='Access code'),
        ),
        migrations.AddField(
            model_name='resource',
            name='access_code_type',
            field=models.CharField(choices=[('none', 'None'), ('pin6', '6-digit pin code')], default='none', max_length=20, verbose_name='Access code type'),
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'permissions': (('can_approve_reservation', 'Can approve reservation'), ('can_view_reservation_access_code', 'Can view reservation access code')), 'verbose_name': 'unit', 'verbose_name_plural': 'units'},
        ),
    ]

