# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-10 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0045_migrate_reservation_info_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='access_code',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Access code'),
        ),
    ]
