# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-29 08:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


NMC_SUPPORTED_FIELDS = ('reserver_name', 'reserver_phone_number', 'reserver_address_street', 'reserver_address_zip',
                        'reserver_address_city', 'billing_address_street', 'billing_address_zip', 'billing_address_city',
                        'company', 'event_description', 'reserver_id', 'number_of_participants', 'reserver_email_address')

NMC_REQUIRED_FIELDS = ('reserver_name', 'reserver_phone_number', 'reserver_address_street', 'reserver_address_zip',
                       'reserver_address_city', 'event_description', 'reserver_id', 'reserver_email_address')

ALL_FIELDS = NMC_SUPPORTED_FIELDS + ('event_subject',)


def create_reservation_metadata_fields_and_set(apps, schema_editor):
    Resource = apps.get_model('resources', 'Resource')
    ReservationMetadataField = apps.get_model('resources', 'ReservationMetadataField')
    ReservationMetadataSet = apps.get_model('resources', 'ReservationMetadataSet')

    for field_name in ALL_FIELDS:
        ReservationMetadataField.objects.create(field_name=field_name)

    data_set = ReservationMetadataSet.objects.create(
        name='default',

    )
    data_set.supported_fields = ReservationMetadataField.objects.filter(field_name__in=NMC_SUPPORTED_FIELDS)
    data_set.required_fields = ReservationMetadataField.objects.filter(field_name__in=NMC_REQUIRED_FIELDS)

    for resource in Resource.objects.filter(need_manual_confirmation=True):
        resource.reservation_metadata_set = data_set
        resource.save(update_fields=('reservation_metadata_set',))


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resources', '0047_period_back_to_basics'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationMetadataField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100, unique=True, verbose_name='Field name')),
            ],
            options={
                'verbose_name_plural': 'Reservation metadata fields',
                'verbose_name': 'Reservation metadata field',
            },
        ),
        migrations.CreateModel(
            name='ReservationMetadataSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Time of creation')),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Time of modification')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservationmetadataset_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservationmetadataset_modified', to=settings.AUTH_USER_MODEL, verbose_name='Modified by')),
                ('required_fields', models.ManyToManyField(blank=True, related_name='metadata_sets_required', to='resources.ReservationMetadataField', verbose_name='Required fields')),
                ('supported_fields', models.ManyToManyField(related_name='metadata_sets_supported', to='resources.ReservationMetadataField', verbose_name='Supported fields')),
            ],
            options={
                'verbose_name_plural': 'Reservation metadata sets',
                'verbose_name': 'Reservation metadata set',
            },
        ),
        migrations.AddField(
            model_name='reservation',
            name='event_subject',
            field=models.CharField(blank=True, max_length=200, verbose_name='Event subject'),
        ),
        migrations.AddField(
            model_name='resource',
            name='reservation_metadata_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resources.ReservationMetadataSet'),
        ),
        migrations.RunPython(create_reservation_metadata_fields_and_set, migrations.RunPython.noop),
    ]
