# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-26 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0050_add_reservation_host_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ('name',), 'permissions': (('can_approve_reservation', 'Can approve reservation'), ('can_view_reservation_access_code', 'Can view reservation access code'), ('can_view_reservation_extra_fields', 'Can view reservation extra fields')), 'verbose_name': 'unit', 'verbose_name_plural': 'units'},
        ),
    ]
