# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-31 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0053_can_view_reservation_catering_orders_perm'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='participants',
            field=models.TextField(blank=True, verbose_name='Participants'),
        ),
    ]
