# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-10 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0059_add_ignore_opening_hours_perm'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipment',
            options={'ordering': ('category', 'name'), 'verbose_name': 'equipment', 'verbose_name_plural': 'equipment'},
        ),
        migrations.AlterModelOptions(
            name='purpose',
            options={'ordering': ('name',), 'verbose_name': 'purpose', 'verbose_name_plural': 'purposes'},
        ),
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ('id',), 'verbose_name': 'reservation', 'verbose_name_plural': 'reservations'},
        ),
        migrations.AlterModelOptions(
            name='resource',
            options={'ordering': ('unit', 'name'), 'verbose_name': 'resource', 'verbose_name_plural': 'resources'},
        ),
        migrations.AlterModelOptions(
            name='resourcetype',
            options={'ordering': ('name',), 'verbose_name': 'resource type', 'verbose_name_plural': 'resource types'},
        ),
        migrations.AlterField(
            model_name='reservation',
            name='state',
            field=models.CharField(choices=[('created', 'created'), ('cancelled', 'cancelled'), ('confirmed', 'confirmed'), ('denied', 'denied'), ('requested', 'requested')], default='confirmed', max_length=16, verbose_name='State'),
        ),
    ]
