# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-13 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0061_add_modify_reservations_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='origin_id',
            field=models.CharField(editable=False, max_length=50, null=True, verbose_name='Original ID'),
        ),
    ]
