# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0064_add_modify_catering_order_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='manager_email',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='Manager email'),
        ),
    ]
