# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-09-07 04:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0067_add_reservation_confirmed_notification_extra'),
        ('resources', '0067_resource_equipments_field'),
    ]

    operations = [
    ]
