# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-09-24 20:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0067_add_reservation_confirmed_notification_extra'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_begin_times_must_match', models.BooleanField(default=False, verbose_name='Reservation begin times must match')),
                ('reservation_end_times_must_match', models.BooleanField(default=False, verbose_name='Reservation end times must match')),
                ('reservation_requires', models.BooleanField(default=False, verbose_name='Reservation requires')),
                ('parent_resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections_where_parent_resource', to='resources.Resource', verbose_name='Parent resource')),
                ('sub_resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections_where_sub_resource', to='resources.Resource', verbose_name='Sub resource')),
            ],
            options={
                'verbose_name': 'Resource connection',
                'verbose_name_plural': 'Resource connections',
            },
        ),
        migrations.AddField(
            model_name='reservation',
            name='parent_reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sub_reservations', to='resources.Reservation', verbose_name='Parent reservation'),
        ),
        migrations.AddField(
            model_name='resource',
            name='sub_resources',
            field=models.ManyToManyField(blank=True, related_name='parent_resources', through='resources.ResourceConnection', to='resources.Resource', verbose_name='Children'),
        ),
        migrations.AlterUniqueTogether(
            name='resourceconnection',
            unique_together=set([('parent_resource', 'sub_resource')]),
        ),
    ]
