# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-31 14:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import enumfields.fields
import resources.enums


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resources', '0068_merge_20180907_0708'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitGroup',
            fields=[
                ('id',
                 models.AutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('created_at',
                 models.DateTimeField(
                     default=django.utils.timezone.now,
                     verbose_name='Time of creation')),
                ('modified_at',
                 models.DateTimeField(
                     default=django.utils.timezone.now,
                     verbose_name='Time of modification')),
                ('name', models.CharField(max_length=200)),
                ('name_fi', models.CharField(max_length=200, null=True)),
                ('name_en', models.CharField(max_length=200, null=True)),
                ('name_sv', models.CharField(max_length=200, null=True)),
                ('created_by',
                 models.ForeignKey(
                     blank=True,
                     null=True,
                     on_delete=django.db.models.deletion.SET_NULL,
                     related_name='unitgroup_created',
                     to=settings.AUTH_USER_MODEL,
                     verbose_name='Created by')),
                ('members',
                 models.ManyToManyField(
                     related_name='unit_groups',
                     to='resources.Unit')),
                ('modified_by',
                 models.ForeignKey(
                     blank=True,
                     null=True,
                     on_delete=django.db.models.deletion.SET_NULL,
                     related_name='unitgroup_modified',
                     to=settings.AUTH_USER_MODEL,
                     verbose_name='Modified by')),
            ],
            options={
                'abstract': False,
                'verbose_name': 'unit group',
                'verbose_name_plural': 'unit groups'
            },
        ),
        migrations.CreateModel(
            name='UnitGroupAuthorization',
            fields=[
                ('id',
                 models.AutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('level',
                 enumfields.fields.EnumField(
                     enum=resources.enums.UnitGroupAuthorizationLevel,
                     max_length=50,
                     verbose_name='authorization level')),
                ('authorized',
                 models.ForeignKey(
                     on_delete=django.db.models.deletion.CASCADE,
                     related_name='unit_group_authorizations',
                     to=settings.AUTH_USER_MODEL,
                     verbose_name='authorized user')),
                ('subject',
                 models.ForeignKey(
                     on_delete=django.db.models.deletion.CASCADE,
                     related_name='authorizations',
                     to='resources.UnitGroup',
                     verbose_name='subject of the authorization')),
            ],
            options={
                'verbose_name': 'unit group authorization',
                'verbose_name_plural': 'unit group authorizations'
            },
        ),
        migrations.AlterUniqueTogether(
            name='unitgroupauthorization',
            unique_together=set([('authorized', 'subject', 'level')]),
        ),
        migrations.CreateModel(
            name='UnitAuthorization',
            fields=[
                ('id',
                 models.AutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('level',
                 enumfields.fields.EnumField(
                     enum=resources.enums.UnitAuthorizationLevel,
                     max_length=50,
                     verbose_name='authorization level')),
                ('authorized',
                 models.ForeignKey(
                     on_delete=django.db.models.deletion.CASCADE,
                     related_name='unit_authorizations',
                     to=settings.AUTH_USER_MODEL,
                     verbose_name='authorized user')),
                ('subject',
                 models.ForeignKey(
                     on_delete=django.db.models.deletion.CASCADE,
                     related_name='authorizations',
                     to='resources.Unit',
                     verbose_name='subject of the authorization')),
            ],
            options={
                'verbose_name': 'unit authorization',
                'verbose_name_plural': 'unit authorizations'
            },

        ),
        migrations.AlterUniqueTogether(
            name='unitauthorization',
            unique_together=set([('authorized', 'subject', 'level')]),
        ),
    ]
