# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-09 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0069_unit_auth'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='reservable_min_days_in_advance',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Days until reservation is possible'),
        ),
        migrations.AddField(
            model_name='unit',
            name='reservable_min_days_in_advance',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Days until reservation is possible'),
        ),
        migrations.RenameField(
            model_name='resource',
            old_name='reservable_days_in_advance',
            new_name='reservable_max_days_in_advance',
        ),
        migrations.RenameField(
            model_name='unit',
            old_name='reservable_days_in_advance',
            new_name='reservable_max_days_in_advance',
        ),
    ]
