# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-19 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0069_unit_auth'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='reservation_instructions',
            field=models.TextField(blank=True, null=True, verbose_name='Reservation instructions'),
        ),
        migrations.AddField(
            model_name='resource',
            name='reservation_instructions_en',
            field=models.TextField(blank=True, null=True, verbose_name='Reservation instructions'),
        ),
        migrations.AddField(
            model_name='resource',
            name='reservation_instructions_fi',
            field=models.TextField(blank=True, null=True, verbose_name='Reservation instructions'),
        ),
        migrations.AddField(
            model_name='resource',
            name='reservation_instructions_sv',
            field=models.TextField(blank=True, null=True, verbose_name='Reservation instructions'),
        ),
    ]
