# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-15 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0069_unit_auth'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='external_calendar_url',
            field=models.URLField(blank=True, null=True, verbose_name='External calendar url'),
        ),
    ]
