# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-12 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0070_resource_reservable_delay_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='reservable_min_days_in_advance',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Days until reservation is possible'),
        ),
    ]
