# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-27 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0070_reservable_min_and_max_days_in_advance'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='usage_instructions',
            field=models.TextField(blank=True, help_text='Optional instructions regarding the use of the resource, including required guide presence', null=True, verbose_name='Usage instructions'),
        ),
        migrations.AddField(
            model_name='resource',
            name='usage_instructions_en',
            field=models.TextField(blank=True, help_text='Optional instructions regarding the use of the resource, including required guide presence', null=True, verbose_name='Usage instructions'),
        ),
        migrations.AddField(
            model_name='resource',
            name='usage_instructions_fi',
            field=models.TextField(blank=True, help_text='Optional instructions regarding the use of the resource, including required guide presence', null=True, verbose_name='Usage instructions'),
        ),
        migrations.AddField(
            model_name='resource',
            name='usage_instructions_sv',
            field=models.TextField(blank=True, help_text='Optional instructions regarding the use of the resource, including required guide presence', null=True, verbose_name='Usage instructions'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='reservation_info',
            field=models.TextField(blank=True, help_text='If there are any special considerations for making reservations, write them here', null=True, verbose_name='Reservation info'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='reservation_info_en',
            field=models.TextField(blank=True, help_text='If there are any special considerations for making reservations, write them here', null=True, verbose_name='Reservation info'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='reservation_info_fi',
            field=models.TextField(blank=True, help_text='If there are any special considerations for making reservations, write them here', null=True, verbose_name='Reservation info'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='reservation_info_sv',
            field=models.TextField(blank=True, help_text='If there are any special considerations for making reservations, write them here', null=True, verbose_name='Reservation info'),
        ),
    ]
