# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-29 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0070_reservable_min_and_max_days_in_advance'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='external_reservation_url',
            field=models.URLField(blank=True, help_text='A link to an external reservation system if this resource is managed elsewhere', null=True, verbose_name='External reservation URL'),
        ),
    ]
