# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-28 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0071_change_translations'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='generate_access_codes',
            field=models.BooleanField(default=True, editable=False, help_text='Should access codes generated by the general system', verbose_name='Generate access codes'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='access_code_type',
            field=models.CharField(choices=[('none', 'None'), ('pin6', '4-digit PIN code'), ('pin6', '6-digit PIN code')], default='none', max_length=20, verbose_name='Access code type'),
        ),
    ]
