# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-04 05:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0071_resource_external_reservation_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='reservable_max_days_in_advance',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Reservable max. days in advance'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='reservable_min_days_in_advance',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Reservable min. days in advance'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='reservation_metadata_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resources.ReservationMetadataSet', verbose_name='Reservation metadata set'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='reservable_max_days_in_advance',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Reservable max. days in advance'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='reservable_min_days_in_advance',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Reservable min. days in advance'),
        ),
    ]
