# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-13 15:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0071_unit_reservable_min_days_in_advance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='reservable_days_in_advance',
            new_name='reservable_max_days_in_advance',
        ),
        migrations.RenameField(
            model_name='unit',
            old_name='reservable_days_in_advance',
            new_name='reservable_max_days_in_advance',
        ),
    ]
