# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-04 06:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0072_reservable_min_and_max_days_verbose_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='authentication',
            field=models.CharField(choices=[('unauthenticated', 'Unauthenticated'), ('none', 'None'), ('weak', 'Weak'), ('strong', 'Strong')], max_length=20, verbose_name='Authentication'),
        ),
    ]
