# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-31 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0072_reservable_min_and_max_days_verbose_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='reservation_requested_notification_extra_en',
            field=models.TextField(blank=True, null=True, verbose_name='Extra content to "reservation requested" notification'),
        ),
        migrations.AddField(
            model_name='resource',
            name='reservation_requested_notification_extra_fi',
            field=models.TextField(blank=True, null=True, verbose_name='Extra content to "reservation requested" notification'),
        ),
        migrations.AddField(
            model_name='resource',
            name='reservation_requested_notification_extra_sv',
            field=models.TextField(blank=True, null=True, verbose_name='Extra content to "reservation requested" notification'),
        ),
    ]
