# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-19 06:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0073_resource_new_authentication_choice'),
    ]

    operations = [
        migrations.CreateModel(
            name='DurationSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.DurationField(verbose_name='Available reservation slot duration')),
            ],
        ),
        migrations.AddField(
            model_name='resource',
            name='reservation_length_type',
            field=models.CharField(choices=[('within_day', 'within day'), ('over_day', 'over day')], default='within_day', max_length=16, verbose_name='Reservations length type'),
        ),
        migrations.AddField(
            model_name='durationslot',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duration_slots', to='resources.Resource'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='duration_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resources.DurationSlot', verbose_name='Resources reservation duration slot'),
        ),
    ]
