# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-11 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0073_add_resource_generate_access_codes_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='area',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Area'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='max_reservations_per_user',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Maximum number of active reservations per user'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='people_capacity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='People capacity'),
        ),
    ]
