# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-31 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0073_add_resource_generate_access_codes_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='reservation_requested_notification_extra_en',
            field=models.TextField(blank=True, null=True, verbose_name='Extra content to "reservation requested" notification'),
        ),
        migrations.AddField(
            model_name='resource',
            name='reservation_requested_notification_extra_fi',
            field=models.TextField(blank=True, null=True, verbose_name='Extra content to "reservation requested" notification'),
        ),
        migrations.AddField(
            model_name='resource',
            name='reservation_requested_notification_extra_sv',
            field=models.TextField(blank=True, null=True, verbose_name='Extra content to "reservation requested" notification'),
        ),
    ]
