# Generated by Django 2.1.5 on 2019-02-27 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0074_reservation_confirmed_notification_extra_translations'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='staff_event',
            field=models.BooleanField(default=False, verbose_name='Is staff event'),
        ),
    ]
