# Generated by Django 2.1.5 on 2019-02-18 12:48

from django.db import migrations, models


def change_negative_fields(apps, schema_editor):
    Resource = apps.get_model('resources', 'Resource')
    for resource in Resource.objects.all():
        resource_has_changed = False
        if resource.area and resource.area < 0:
            resource.area = 0
            resource_has_changed = True
        if resource.max_reservations_per_user and resource.max_reservations_per_user < 0:
            resource.max_reservations_per_user = 0
            resource_has_changed = True
        if resource.people_capacity and resource.people_capacity < 0:
            resource.people_capacity = 0
            resource_has_changed = True
        if resource_has_changed:
            resource.save()


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0074_reservation_confirmed_notification_extra_translations'),
    ]

    operations = [
        migrations.RunPython(change_negative_fields),
        migrations.AlterField(
            model_name='resource',
            name='area',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Area (m2)'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='max_reservations_per_user',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Maximum number of active reservations per user'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='people_capacity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='People capacity'),
        ),
    ]
