# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-29 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0074_reservation_length_type_and_duration_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='use_payments',
            field=models.BooleanField(default=False, verbose_name='Chargeable through payments system'),
        ),
    ]
