# Generated by Django 2.1.5 on 2019-02-28 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0075_alter_resource_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='staff_event',
            field=models.BooleanField(default=False, verbose_name='Is staff event'),
        ),
    ]
