# Generated by Django 2.1.7 on 2019-04-18 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0075_alter_resource_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessibilityViewpoint',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nimi')),
                ('name_fi', models.CharField(max_length=200, null=True, verbose_name='Nimi')),
                ('name_en', models.CharField(max_length=200, null=True, verbose_name='Nimi')),
                ('name_sv', models.CharField(max_length=200, null=True, verbose_name='Nimi')),
                ('order_text', models.CharField(default='0', max_length=200, verbose_name='Tilaus')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Lisäysaika')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Muokkausaika')),
            ],
            options={
                'verbose_name': 'accessibility viewpoint',
                'verbose_name_plural': 'accessibility viewpoints',
                'ordering': ('order_text',),
            },
        ),
        migrations.CreateModel(
            name='ResourceAccessibility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(choices=[(20, 'green'), (10, 'unknown'), (0, 'red')], verbose_name='Accessibility level')),
                ('order', models.IntegerField(verbose_name='Resource ordering priority')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Lisäysaika')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Muokkausaika')),
            ],
            options={
                'verbose_name': 'varaus',
                'verbose_name_plural': 'varaukset',
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='resourceaccessibility',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_accessibilities', to='resources.Resource', verbose_name='Resurssi'),
        ),
        migrations.AddField(
            model_name='resourceaccessibility',
            name='viewpoint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_accessibilities', to='resources.AccessibilityViewpoint', verbose_name='Resource Accessibility'),
        ),
        migrations.AlterUniqueTogether(
            name='resourceaccessibility',
            unique_together={('viewpoint', 'resource')},
        ),
    ]
