# Generated by Django 2.1.7 on 2019-04-25 10:50

import datetime
from django.db import migrations, models


def set_existing_resources_slot_size(apps, schema_editor):
    Resource = apps.get_model('resources', 'Resource')
    for resource in Resource.objects.all():
        resource.slot_size = resource.min_period
        resource.save()


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0076_reservation_staff_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='slot_size',
            field=models.DurationField(default=datetime.timedelta(0, 1800),
                                       verbose_name='Slot size for reservation time'),
        ),
        migrations.RunPython(set_existing_resources_slot_size),
    ]
