# Generated by Django 2.1.7 on 2019-06-13 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0077_resource_slot_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='reservation_extra_questions',
            field=models.TextField(blank=True, null=True, verbose_name='Reservation extra questions'),
        ),
    ]
