# Generated by Django 2.1.7 on 2019-05-24 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0077_resource_slot_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='opening_hours_are_editable',
            field=models.BooleanField(default=True, verbose_name='Opening hours are editable'),
        ),
    ]
