# Generated by Django 2.1.7 on 2019-06-19 10:04

from django.db import migrations, models


def create_db_entry_for_extra_questions(apps, schema_editor):
    ReservationMetadataField = apps.get_model('resources', 'ReservationMetadataField')
    if not ReservationMetadataField.objects.filter(field_name='reservation_extra_questions').exists():
        ReservationMetadataField.objects.create(field_name='reservation_extra_questions')


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0078_accessibility_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='reservation_extra_questions',
            field=models.TextField(blank=True, verbose_name='Reservation extra questions'),
        ),
        migrations.AddField(
            model_name='resource',
            name='reservation_extra_questions',
            field=models.TextField(blank=True, verbose_name='Reservation extra questions'),
        ),
        migrations.RunPython(create_db_entry_for_extra_questions, migrations.RunPython.noop),
    ]
