# Generated by Django 2.1.7 on 2019-06-18 04:40

from django.db import migrations, models


def create_db_entry_for_extra_questions(apps, schema_editor):
    ReservationMetadataField = apps.get_model('resources', 'ReservationMetadataField')
    ReservationMetadataField.objects.create(field_name='reservation_extra_questions')


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0078_resource_reservation_extra_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='reservation_extra_questions',
            field=models.TextField(blank=True, null=True, verbose_name='Reservation extra questions'),
        ),
        migrations.RunPython(create_db_entry_for_extra_questions),
    ]
