# Generated by Django 2.1.9 on 2019-09-03 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0080_payments_related_changes'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='type',
            field=models.CharField(choices=[('normal', 'Normal reservation'), ('blocked', 'Resource blocked')], default='normal', max_length=32, verbose_name='Type'),
        ),
    ]
