# Generated by Django 2.1.7 on 2019-06-27 13:44

from django.db import migrations, models

NEW_FIELDS = ('billing_first_name', 'billing_last_name', 'billing_email_address', 'billing_phone_number')


def create_new_metadata_fields(apps, schema_editor):
    ReservationMetadataField = apps.get_model('resources', 'ReservationMetadataField')
    for field_name in NEW_FIELDS:
        ReservationMetadataField.objects.get_or_create(field_name=field_name)


def delete_new_metadata_fields(apps, schema_editor):
    ReservationMetadataField = apps.get_model('resources', 'ReservationMetadataField')
    ReservationMetadataField.objects.filter(field_name__in=NEW_FIELDS).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0080_add_can_modify_paid_reservations_perm'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='billing_email_address',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Billing email address'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='billing_first_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Billing first name'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='billing_last_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Billing last name'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='billing_phone_number',
            field=models.CharField(blank=True, max_length=30, verbose_name='Billing phone number'),
        ),
        migrations.RunPython(create_new_metadata_fields, delete_new_metadata_fields),
    ]
