# Generated by Django 2.1.9 on 2019-09-26 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0081_reservation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='data_source',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='External data source'),
        ),
        migrations.AddField(
            model_name='unit',
            name='data_source_hours',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='External data source for opening hours'),
        ),
    ]
