# Generated by Django 2.2.9 on 2020-02-26 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0086_more_additions_to_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='payment_terms',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources_where_payment_terms', to='resources.TermsOfUse', verbose_name='Payment terms'),
        ),
        migrations.AddField(
            model_name='termsofuse',
            name='terms_type',
            field=models.CharField(choices=[('payment_terms', 'Payment terms'), ('generic_terms', 'Generic terms')], default='generic_terms', max_length=40, verbose_name='Terms type'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='generic_terms',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources_where_generic_terms', to='resources.TermsOfUse', verbose_name='Generic terms'),
        ),
    ]
