# Generated by Django 2.2.10 on 2020-03-12 10:25

from django.db import migrations


def copy_templates(apps, schema_editor):
    OldNotificationTemplate = apps.get_model('notifications', 'NotificationTemplate')
    NotificationTemplate = apps.get_model('django_ilmoitin', 'NotificationTemplate')
    NotificationTemplateTranslation = apps.get_model('django_ilmoitin', 'NotificationTemplateTranslation')
    all_notification_templates = OldNotificationTemplate.objects.all()

    for old_tmpl in OldNotificationTemplate.objects.all():
        new_tmpl = NotificationTemplate.objects.create(type=old_tmpl.type)
        for trans in old_tmpl.translations.values():
            new_tmpl.set_current_language(trans['language_code'])
            new_tmpl.subject = trans['subject']
            new_tmpl.body_text = trans['body']
            new_tmpl.body_html = trans['html_body']
            new_tmpl.save()

class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0087_add_payment_terms'),
        ('notifications', '0005_add_access_code_created_notification')
    ]

    operations = [
        migrations.RunPython(copy_templates),
    ]
