# Generated by Django 2.2.9 on 2020-03-10 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0087_add_payment_terms'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accessibilityvalue',
            options={'ordering': ('order',), 'verbose_name': 'saavutettavuusarvo', 'verbose_name_plural': 'saavutettavuusarvot'},
        ),
        migrations.AlterModelOptions(
            name='accessibilityviewpoint',
            options={'ordering': ('order_text',), 'verbose_name': 'saavutettavuusnäkökulma', 'verbose_name_plural': 'saavutettavuusnäkökulmat'},
        ),
        migrations.AlterModelOptions(
            name='resourceaccessibility',
            options={'ordering': ('id',), 'verbose_name': 'resurssin saavutettavuuden yhteenveto', 'verbose_name_plural': 'resurssin saavutettavuuden yhteenvedot'},
        ),
        migrations.AlterModelOptions(
            name='resourcegroup',
            options={'ordering': ('name',), 'permissions': [('group:can_approve_reservation', 'Can approve reservation'), ('group:can_make_reservations', 'Can make reservations'), ('group:can_modify_reservations', 'Can modify reservations'), ('group:can_ignore_opening_hours', 'Can make reservations outside opening hours'), ('group:can_view_reservation_access_code', 'Can view reservation access code'), ('group:can_view_reservation_extra_fields', 'Can view reservation extra fields'), ('group:can_view_reservation_user', 'Can view reservation user'), ('group:can_access_reservation_comments', 'Can access reservation comments'), ('group:can_comment_reservations', 'Can create comments for a reservation'), ('group:can_view_reservation_catering_orders', 'Can view reservation catering orders'), ('group:can_modify_reservation_catering_orders', 'Can modify reservation catering orders'), ('group:can_view_reservation_product_orders', 'Can view reservation product orders'), ('group:can_modify_paid_reservations', 'Can modify paid reservations'), ('group:can_bypass_payment', 'Can bypass payment for paid reservations'), ('group:can_create_staff_event', 'Can create a reservation that is a staff event'), ('group:can_create_special_type_reservation', 'Can create reservations of a non-normal type'), ('group:can_bypass_manual_confirmation', 'Can bypass manual confirmation requirement for resources'), ('group:can_create_reservations_for_other_users', 'Can create reservations for other registered users'), ('group:can_create_overlapping_reservations', 'Can create overlapping reservations')], 'verbose_name': 'Resource group', 'verbose_name_plural': 'Resource groups'},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ('name',), 'permissions': [('unit:can_approve_reservation', 'Can approve reservation'), ('unit:can_make_reservations', 'Can make reservations'), ('unit:can_modify_reservations', 'Can modify reservations'), ('unit:can_ignore_opening_hours', 'Can make reservations outside opening hours'), ('unit:can_view_reservation_access_code', 'Can view reservation access code'), ('unit:can_view_reservation_extra_fields', 'Can view reservation extra fields'), ('unit:can_view_reservation_user', 'Can view reservation user'), ('unit:can_access_reservation_comments', 'Can access reservation comments'), ('unit:can_comment_reservations', 'Can create comments for a reservation'), ('unit:can_view_reservation_catering_orders', 'Can view reservation catering orders'), ('unit:can_modify_reservation_catering_orders', 'Can modify reservation catering orders'), ('unit:can_view_reservation_product_orders', 'Can view reservation product orders'), ('unit:can_modify_paid_reservations', 'Can modify paid reservations'), ('unit:can_bypass_payment', 'Can bypass payment for paid reservations'), ('unit:can_create_staff_event', 'Can create a reservation that is a staff event'), ('unit:can_create_special_type_reservation', 'Can create reservations of a non-normal type'), ('unit:can_bypass_manual_confirmation', 'Can bypass manual confirmation requirement for resources'), ('unit:can_create_reservations_for_other_users', 'Can create reservations for other registered users'), ('unit:can_create_overlapping_reservations', 'Can create overlapping reservations')], 'verbose_name': 'unit', 'verbose_name_plural': 'units'},
        ),
        migrations.AlterModelOptions(
            name='unitaccessibility',
            options={'ordering': ('id',), 'verbose_name': 'toimipisteen saavutettavuuden yhteenveto', 'verbose_name_plural': 'toimipisteen saavutettavuuden yhteenvedot'},
        ),
        migrations.AddField(
            model_name='unit',
            name='disallow_overlapping_reservations',
            field=models.BooleanField(default=False, verbose_name='Disallow overlapping reservations in this unit'),
        ),
        migrations.AlterField(
            model_name='accessibilityvalue',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Lisäysaika'),
        ),
        migrations.AlterField(
            model_name='accessibilityvalue',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Muokkausaika'),
        ),
        migrations.AlterField(
            model_name='accessibilityvalue',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Järjestysprioriteetti'),
        ),
        migrations.AlterField(
            model_name='accessibilityvalue',
            name='value',
            field=models.CharField(max_length=128, unique=True, verbose_name='Saavutettavuusyhteenvedon arvo'),
        ),
        migrations.AlterField(
            model_name='accessibilityviewpoint',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Lisäysaika'),
        ),
        migrations.AlterField(
            model_name='accessibilityviewpoint',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Muokkausaika'),
        ),
        migrations.AlterField(
            model_name='accessibilityviewpoint',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nimi'),
        ),
        migrations.AlterField(
            model_name='accessibilityviewpoint',
            name='name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Nimi'),
        ),
        migrations.AlterField(
            model_name='accessibilityviewpoint',
            name='name_fi',
            field=models.CharField(max_length=200, null=True, verbose_name='Nimi'),
        ),
        migrations.AlterField(
            model_name='accessibilityviewpoint',
            name='name_sv',
            field=models.CharField(max_length=200, null=True, verbose_name='Nimi'),
        ),
        migrations.AlterField(
            model_name='accessibilityviewpoint',
            name='order_text',
            field=models.CharField(default='0', max_length=200, verbose_name='Tilaus'),
        ),
        migrations.AlterField(
            model_name='resourceaccessibility',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Lisäysaika'),
        ),
        migrations.AlterField(
            model_name='resourceaccessibility',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Muokkausaika'),
        ),
        migrations.AlterField(
            model_name='resourceaccessibility',
            name='order',
            field=models.IntegerField(verbose_name='Resurssin järjestysprioriteetti'),
        ),
        migrations.AlterField(
            model_name='resourceaccessibility',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessibility_summaries', to='resources.Resource', verbose_name='Resurssi'),
        ),
        migrations.AlterField(
            model_name='resourceaccessibility',
            name='value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.AccessibilityValue', verbose_name='Saavutettavuusyhteenvedon arvo'),
        ),
        migrations.AlterField(
            model_name='resourceaccessibility',
            name='viewpoint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_accessibility_summaries', to='resources.AccessibilityViewpoint', verbose_name='Resurssin saavutettavuus'),
        ),
        migrations.AlterField(
            model_name='unitaccessibility',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Lisäysaika'),
        ),
        migrations.AlterField(
            model_name='unitaccessibility',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Muokkausaika'),
        ),
        migrations.AlterField(
            model_name='unitaccessibility',
            name='order',
            field=models.IntegerField(verbose_name='Resurssin järjestysprioriteetti'),
        ),
        migrations.AlterField(
            model_name='unitaccessibility',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessibility_summaries', to='resources.Unit', verbose_name='Resurssi'),
        ),
        migrations.AlterField(
            model_name='unitaccessibility',
            name='value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.AccessibilityValue', verbose_name='Saavutettavuusyhteenvedon arvo'),
        ),
        migrations.AlterField(
            model_name='unitaccessibility',
            name='viewpoint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_accessibility_summaries', to='resources.AccessibilityViewpoint', verbose_name='Resurssin saavutettavuus'),
        ),
    ]
