# Generated by Django 2.2.10 on 2020-03-25 10:12

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0089_changes_to_resource_price_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='max_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Max price'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='min_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Min price'),
        ),
    ]
