# Generated by Django 2.2.13 on 2020-08-03 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resources', '0091_add_two_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationCancelReasonCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Time of creation')),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Time of modification')),
                ('reservation_type', models.CharField(choices=[('confirmed', 'Confirmed reservation'), ('requested', 'Requested reservation'), ('own', 'Own reservation')], default='confirmed', max_length=32, verbose_name='Reservation type')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('name_fi', models.CharField(max_length=100, null=True, unique=True, verbose_name='Name')),
                ('name_en', models.CharField(max_length=100, null=True, unique=True, verbose_name='Name')),
                ('name_sv', models.CharField(max_length=100, null=True, unique=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('description_fi', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('description_sv', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservationcancelreasoncategory_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservationcancelreasoncategory_modified', to=settings.AUTH_USER_MODEL, verbose_name='Modified by')),
            ],
            options={
                'verbose_name': 'Reservation cancellation reason category',
                'verbose_name_plural': 'Reservation cancellation reason categories',
            },
        ),
        migrations.CreateModel(
            name='ReservationCancelReason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Time of creation')),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Time of modification')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='resources.ReservationCancelReasonCategory')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservationcancelreason_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservationcancelreason_modified', to=settings.AUTH_USER_MODEL, verbose_name='Modified by')),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cancel_reason', to='resources.Reservation')),
            ],
            options={
                'verbose_name': 'Reservation cancellation reason',
                'verbose_name_plural': 'Reservation cancellation reasons',
            },
        ),
    ]
