# Generated by Django 2.2.13 on 2020-09-03 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0093_resource_email_attachments'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultidaySettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_days', models.IntegerField(verbose_name='Max days')),
                ('min_days', models.IntegerField(verbose_name='Min days')),
                ('check_in_time', models.TimeField(blank=True, null=True, verbose_name='Check-in time')),
                ('check_out_time', models.TimeField(blank=True, null=True, verbose_name='Check-out time')),
            ],
            options={
                'verbose_name': 'Multiday period settings',
            },
        ),
        migrations.AddField(
            model_name='period',
            name='reservation_length_type',
            field=models.CharField(choices=[('within_day', 'within day'), ('whole_day', 'whole day'), ('over_night', 'over night')], default='within_day', max_length=16, verbose_name='Reservations length type'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='reservation_length_type',
            field=models.CharField(choices=[('within_day', 'within day'), ('whole_day', 'whole day'), ('over_night', 'over night')], default='within_day', max_length=16, verbose_name='Length type'),
        ),
        migrations.CreateModel(
            name='MultidayStartDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(verbose_name='Start day')),
                ('multiday_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_days', to='resources.MultidaySettings', verbose_name='Multiday settings')),
            ],
            options={
                'verbose_name': 'Multiday start settings',
            },
        ),
        migrations.AddField(
            model_name='multidaysettings',
            name='period',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='multiday_settings', to='resources.Period'),
        ),
    ]
