# Generated by Django 2.2.13 on 2020-09-04 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0094_accessibility_shortage_counts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='attachments',
            field=models.ManyToManyField(blank=True, to='resources.Attachment', verbose_name='Attachments'),
        ),
    ]
