# Generated by Django 2.2.13 on 2020-09-09 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0095_auto_20200904_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='multidaysettings',
            name='must_end_on_start_day',
            field=models.BooleanField(default=False, verbose_name='Must end on start day'),
        ),
    ]
